[package]
name = "v2ray-rust"
version = "0.1.0"
authors = ["darsvador"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.10.0"
actix-http = { version = "3.0.0-beta.5", features = ["rustls"]}
actix-rt = "2.2.0"
env_logger = "0.9"
actix-server = "2.0.0-rc.4"
log = "0.4"
awc = "3.0.0-beta.4"
actix-service = "2.0"
snmalloc-rs = "0.2.6"
anyhow = "1.0"
bytes = "1"
rand = { version = "0.7", features = ["small_rng"] }
crypto2 = "0.1.2"
num_cpus = "1.13.0"
futures = "0.3.1"
tokio = {version="1", features=["net","io-util","macros"]}
futures-util = "0.3"
bloomfilter = "1.0.2"
byte_string = "1.0"
spin = "0.7.0"
crc32fast = "1.3.0"
uuid = { version="0.8", features=["std"]}
domain_matcher={git="https://github.com/Qv2ray/DomainMatcher/"}
cidr_matcher={git="https://github.com/Qv2ray/CIDRMatcher"}
generator={git="https://github.com/darsvador/generator/"}
ring = { version  = "0.16", optional = true  }

[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))'.dependencies]
shadowsocks-crypto = { version = "0.2.5", features = ["ring"] }

[target.'cfg(any(target_arch = "arm", target_arch = "aarch64"))'.dependencies]
shadowsocks-crypto = { version = "0.2.5", features = ["ring"] }

[target.'cfg(not(any(target_arch = "x86", target_arch = "x86_64", target_arch = "arm", target_arch = "aarch64")))'.dependencies]
shadowsocks-crypto = { version = "0.2.5", features = [] }
