[package]
name = "v2ray-rust"
version = "0.1.0"
authors = ["DuckVador"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smol = "1.2.4"
cidr_matcher = { path="unpulished_crate/CIDRMatcher"}
domain_matcher = {path="unpulished_crate/DomainMatcher"}
bytes = "0.6.0"
