default_outbound = "out"

[[ss]]
addr = "127.0.0.1:9000"
password = "123456"
method = "chacha20-poly1305"
tag = "ss"

[[vmess]]
addr = "127.0.0.1:10002"
uuid = "b831381d-6324-4d53-ad4f-8cda48b30811"
method = "aes-128-gcm"
tag = "v"

[[ws]]
uri = "ws://127.0.0.1:10002/"
tag = "w"

[[direct]]
tag = "d"

[[outbounds]]
chain = ["d"]
# debug
tag = "out"

[[outbounds]]
chain = ["w","v","ss"]
# debug
tag = "out2"

[[inbounds]]
addr = "127.0.0.1:1087"

[[geosite_rules]]
tag = "d"
file_path = "/usr/share/v2ray/geosite.dat"
rules = ["cn"]

[[geoip_rules]]
tag = "d"
file_path = "/usr/share/v2ray/geoip.dat"
rules = ["cn"]
