default_outbound = "cn"

[[ss]]
addr = "127.0.0.1:9000"
password = "123456"
# method = "chacha20-poly1305"
method = "none"
tag = "ss"

[[vmess]]
addr = "127.0.0.1:10002"
uuid = "b831381d-6324-4d53-ad4f-8cda48b30811"
method = "aes-128-gcm"
tag = "v"

[[trojan]]
addr = "127.0.0.1:10002"
password = "password"
tag = "t"

[[ws]]
uri = "ws://127.0.0.1:10002/"
tag = "w"

[[direct]]
tag = "d"

[[outbounds]]
chain = ["ss"]
# debug
tag = "cn"

[[outbounds]]
chain = ["d"]
tag = "private"

[[inbounds]]
addr = "127.0.0.1:1087"
enable_udp = true

# [[dokodemo]]
# addr = "127.0.0.1:12345"
# tproxy = true

[[geosite_rules]]
tag = "cn"
file_path = "/usr/share/v2ray/geosite.dat"
rules = ["cn"]

[[geoip_rules]]
tag = "cn"
file_path = "/usr/share/v2ray/geoip.dat"
rules = ["cn"]

[[geoip_rules]]
tag="private"
file_path = "/usr/share/v2ray/geoip.dat"
rules = ["private"]
